### ISSUE TITLE
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1

### ISSUE THREAD

**Issue by hiluo** [jaredrummler/AndroidProcesses#50]
backtrace
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at Stat.getComm(Stat.java:198)
	at AndroidProcess.getProcessName(AndroidProcess.java:44)
	at AndroidProcess.<init>(AndroidProcess.java:65)
	at AndroidAppProcess.<init>(AndroidAppProcess.java:48)
```

**Comment by hiluo** [comment]
I think of a solution
  ```
 public String getComm() {
-    return fields[1].replace("(", "").replace(")", "");
+    String comm = null;
+    try {
+      comm = fields[1].replace("(", "").replace(")", "");
+    } catch (Exception ignore) {
+      // FIXME: 17/6/23 Temporarily ignore
+    }
+    return comm;
   }

   /**
```
